Gbo
chime-experiment/ch_util pull request #15
Opened 2021-03-12 00:53 UTC by leungcalvin

Refactored ephemeris and some modifications for GBO/TONE outrigger.

2021-03-12 02:08 UTC, jrs65 requested changes
Hi @leungcalvin 

This is looking good, and I don't think it needs a huge amount more work before it's ready to merge. Here are some initial comments:
- Please rebase this into a set of logical commits with messages following our dev guidelines (https://github.com/chime-experiment/Pipeline/blob/master/CONTRIBUTING.md#rules). I'll leave you to figure out exactly what to do, but you need at least these changes in separate commits: changing the default location for CHIME; adding support for changing the observatory to the delay/fringestop routines; and adding support for TONE.
- I'm a bit averse to having a dump of all the antennas in directly, just because it dumps in a lot of redundant info. Can you wrap it up into something which programmatically generates them?
- There's a lot of commented out lines (e.g. old params, print statements, etc). Please tidy those up.
- Please fix up the merge conflicts, I think the CI won't run until you have.

2021-03-12 02:08 UTC, jrs65 commented on ch_util/tools.py
> +            """A hack to return GBO correlator inputs."""
This should be a comment not a docstring.

2021-03-31 03:35 UTC, leungcalvin commented
> Hi @leungcalvin
> 
> This is looking good, and I don't think it needs a huge amount more work before it's ready to merge. Here are some initial comments:
> 
> * Please rebase this into a set of logical commits with messages following our dev guidelines (https://github.com/chime-experiment/Pipeline/blob/master/CONTRIBUTING.md#rules). I'll leave you to figure out exactly what to do, but you need at least these changes in separate commits: changing the default location for CHIME; adding support for changing the observatory to the delay/fringestop routines; and adding support for TONE.
> * I'm a bit averse to having a dump of all the antennas in directly, just because it dumps in a lot of redundant info. Can you wrap it up into something which programmatically generates them?
> * There's a lot of commented out lines (e.g. old params, print statements, etc). Please tidy those up.
> * Please fix up the merge conflicts, I think the CI won't run until you have.

Hi Richard,

I've addressed these comments in a series of logically-chunked commits.

2021-04-26 15:37 UTC, jrs65 requested changes
Hi Calvin, there's two minor changes suggested, and then I think we're done.

2021-04-26 15:37 UTC, jrs65 commented on ch_util/ephemeris.py
> +# Calvin derived the horizontal position of the geometric center of the focal lines and the elevation of the focal line from survey coordinates:
I think you have a doclib entry about this, right? Please put a reference to it in here.

2021-04-26 15:37 UTC, jrs65 commented on ch_util/tools.py
> +    # print("delay_ref", delay_ref)
Please remove all of these commented out print lines.

2021-04-26 15:41 UTC, jrs65 commented
Oh also @leungcalvin when you're done, please rebase this such that only the actual relevant commits are left. I think that should be the three `feat(...)` ones and the `test` one.

2021-04-26 21:09 UTC, jrs65 submitted a review, later dismissed

2021-04-28 17:56 UTC, jrs65 approved these changes

2021-04-28 17:56 UTC, merged