Parallel RFI filtering
chime-experiment/ch_util pull request #35
Opened 2022-08-16 21:32 UTC by ljgray

In its current implementation, the RFI Filter step of the daily pipeline takes ~25 minutes. Most of this time is spent taking a rolling median, and it is done in a single process. This PR should address the issue by pre-calculating a median across frequencies to flatten the auto vis. data, then distributing across the frequency axis to distribute the computation across processes.

2022-08-16 22:24 UTC, jrs65 requested changes

2022-08-16 22:24 UTC, jrs65 commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
Weirdly, I've already fixed this up somewhere, but the commit must have been lost in all of the merging and rebasing we've been doing.

Ideally there should only be one `invert_no_zero` routine and it should support both arguments. I think you can do that via:
```suggestion
    out = np.zeros_like(x)
    np.divide(1, x, out=out.view(np.ndarray), where=x != 0)
    return out
```
and then just remove the `_mpi` version.

Also note that there is a much faster implementation of this available in `draco` at (https://github.com/radiocosmology/draco/blob/master/draco/util/tools.py#L226). The problem with using it is that `ch_util` doesn't have a dependency on `draco` at the moment.

2022-08-16 22:24 UTC, jrs65 commented on ch_util/tools.py
> +def invert_no_zero_mpi(x):
I think you can remove this.

2022-08-16 22:24 UTC, jrs65 commented on ch_util/tools.py
> +from caput import pfb, mpiarray
You could also remove this import with the changes below.

2022-08-16 22:24 UTC, jrs65 commented on ch_util/rfi.py
> +        static_flag = _sf
Seems like you should probably use `MPIArray.wrap` in here.

2022-08-16 22:24 UTC, jrs65 commented on ch_util/rfi.py
> +    data, fwidth=64, twidth=42, threshold=5.0, freq_flat=True, mask=True, mfd=None
I don't think this parallelisation does quite the same thing as the original.

As you only feed it the limited range of frequencies it can only compute a window from within that range. What you want is the windowed median evaluated at the points within the frequency range, but with the frequencies included within that window extending beyond the local range.

Practically each ranks call to `mad_cut_rolling` needs to get passed the *entire* freq-time array, but be told to only evaluate the windowed median for frequencies within a specific range (corresponding to what would be the local frequencies).

2022-08-16 22:24 UTC, jrs65 commented on ch_util/rfi.py
> +
It's not clear to me that this is necessary. You can calculate the median over frequency even for data that is frequency distributed (modulo some messing around with `.local_array` as median doesn't work directly with MPIArrays), which I think is all this is doing.

2022-08-16 22:32 UTC, ljgray commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
Interesting about the draco one, althoughI understand the dependency issue. At the moment, this won't work for mpiarrays after the new updates because "where" operations aren't supported. In`np.divide`, it tries to call `where` in all 3 spots that x exists, so we can only really pass `np.ndarray` into it, unless we update

2022-08-16 22:33 UTC, ljgray commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
We could merge the functionality into a single function which checks for type first though

2022-08-16 22:38 UTC, ljgray commented on ch_util/rfi.py
> +
Apologies, I think I removed that already

2022-08-16 22:44 UTC, ljgray commented on ch_util/rfi.py
> +        static_flag = _sf
I had tried that and was having some funky behaviour with `.redistribute`. Some intermediate calls are removed now so it might work properly now, I'll play with it

2022-08-16 22:45 UTC, jrs65 commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
I think it would work actually fine, the `.view` call is effectively a `.local_array` call, but one which works on `np.ndarray`'s too.

2022-08-16 22:48 UTC, jrs65 commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
Oh sorry. You also need an `x.view(np.ndarray)`

2022-08-16 22:48 UTC, ljgray commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
Do you mean passing the local array to the function only? If I run just those lines where x is a `MPIArray` it gives a `UnsupportedOperation` error

2022-08-16 22:50 UTC, jrs65 commented on ch_util/tools.py
> +    return np.divide(1, x, out=np.zeros_like(x), where=x != 0)
i.e. this is fine
```python
from caput import mpiarray
import numpy as np

x = mpiarray.MPIArray((4, 4), dtype=np.float64)
x[:] = 3

out = np.zeros_like(x)

np.divide(1, x.view(np.ndarray), out=out.view(np.ndarray), where=a != 0)
```

2022-08-16 23:30 UTC, ljgray commented
Although the products aren't quite right yet, this reduces the `RFIFilter` step down to ~15 seconds in a daily pipeline run

2022-08-17 18:50 UTC, ljgray commented
Depends on radiocosmology/caput#210

2022-08-17 22:21 UTC, ljgray commented
Depends on radiocosmology/caput#211

2022-08-18 00:04 UTC, ljgray commented
I've confirmed that this is working, running a full daily pipeline test to make sure there are no surprises and/or the data products don't get changed.

2022-08-19 18:22 UTC, ljgray commented
@jrs65 this produces the same mask now as previous revisions, so it should be good to go unless there are additional changes.

2022-09-06 20:58 UTC, jrs65 approved these changes
Approved, but please quickly change the comment, and condense the commits (if it makes sense to do so), before merging.

2022-09-06 20:58 UTC, jrs65 commented on ch_util/rfi.py
> +        Data is limited to this range in the freqeuncy axis. Defaults to Ellipsis.
Maybe change the comment as the default is not actually an Ellipsis (even though it's effectively the same).

2022-09-06 21:00 UTC, ljgray commented on ch_util/rfi.py
> +        Data is limited to this range in the freqeuncy axis. Defaults to Ellipsis.
Ah, good catch, that's a remnant of a previous way I had tried implementing it

2022-09-06 21:32 UTC, merged