Adding extra static RFI flagging based on time stamps
chime-experiment/ch_util pull request #45
Opened 2022-12-19 22:11 UTC by hgan0

As discussed in the power spectrum workshop, the following bands are added to the RFI flagging routine:      

(1) 505.85 - 511.71 MHz: 6 MHz band (reported by Simon) applied to all CSDs
(2) 584.00 - 590.00 MHz & 596.00 - 602.00 MHz: UHF TV channels 33 & 35 (reported by Seth) applied from CSD 2983
(3) 617.00 - 627.00 MHz: Rogers’ new 600 MHz band (reported by Seth) applied from CSD 2243
(4) 716.00 - 728.00 MHz: Blobs, channels 55 & 56 applied from CSD 2080

Each flagging band in **bad_frequencies** now has a corresponding time stamp (start observing time in UNIX time).
`frequency_mask` has an extra  **timestamp** input to compare with the start observing time of each flagging band. 
`static_rfi_mask_hook` in `ch_pipeline/analysis/flagging.py` needs an extra **timestamp** input.

2023-01-25 21:56 UTC, jrs65 requested changes
This is looking great!

I've suggested a few changes (and you'll need to make some more to make them consistent).

2023-01-25 21:56 UTC, jrs65 commented on ch_util/rfi.py
>      [
```suggestion
bad_frequencies = [
```

2023-01-25 21:56 UTC, jrs65 commented on ch_util/rfi.py
> +        [[], [449.41, 450.98]],
```suggestion
        [None, [449.41, 450.98]],
```

2023-01-25 21:56 UTC, jrs65 commented on ch_util/rfi.py
> +        ],  # from CSD 2893 (2021/10/09 - ) UHF TV Channel 33 (reported by Seth)
Probably better for format like this:
```suggestion
        # from CSD 2893 (2021/10/09 - ) UHF TV Channel 33 (reported by Seth)
        [1633758888, [584.00, 590.00]],  
```

2023-01-25 21:56 UTC, jrs65 commented on ch_util/rfi.py
>  )
```suggestion
]
```

2023-01-25 21:56 UTC, jrs65 commented on ch_util/rfi.py
> +def frequency_mask(timestamp, freq_centre, freq_width=None):
```suggestion
def frequency_mask(freq_centre, timestamp=None, freq_width=None):
```

Put some code like:
```
if timestamp is None:
    timestamp = ctime.ensure_unix(datetime.datetime.now())
```

2023-01-25 21:56 UTC, jrs65 commented on ch_util/rfi.py
> +        ~frequency_mask(data.time[0], data.freq)
```suggestion
        ~frequency_mask(data.freq, timestamp=data.time[0])
```

2023-02-01 20:19 UTC, jrs65 submitted a review, later dismissed
This is looking great. I have some changes to request, but they're pretty much all stylistic. Feel free to ask if you have any questions about them.

When you're done we can look at getting it all merged. You'll either need to rebase all your commits into something cleaner, or squash merge them down with an appropriate commit message (https://github.com/chime-experiment/Pipeline/blob/master/CONTRIBUTING.md#-commit-message-guidelines). Typically we like to "hide how the sausage is made", and just have commits corresponding to externally interesting changes and not include all the minor steps and fixes you had on the way.

2023-02-01 20:19 UTC, jrs65 commented on ch_util/rfi.py
> +    # from CSD 2080 (2019/07/21 - ) Blobs, Channels 55 and 56
I would put comments on top, and leave some new lines to make this easier to read
```suggestion
    # Bad bands at first light
    [None, [449.41, 450.98]],
    [None, [454.88, 456.05]],
    [None, [457.62, 459.18]],
    [None, [483.01, 485.35]],
    [None, [487.70, 494.34]],
    [None, [497.85, 506.05]],
    [None, [529.10, 536.52]],
    [None, [541.60, 554.49]],
    [None, [564.65, 585.35]],
    [None, [693.16, 693.55]],
    [None, [694.34, 696.68]],
    [None, [729.88, 745.12]],
    [None, [746.29, 756.45]],
    
    # 6 MHz band (reported by Simon)
    [None, [505.85, 511.71]],
    
    # from CSD 2893 (2021/10/09 - ) UHF TV Channel 33 (reported by Seth)
    [1633758888, [584.00, 590.00]],
    
    # UHF TV Channel 35
    [1633758888, [596.00, 602.00]],
    
    # from CSD 2243 (2019/12/31 - ) Rogers’ new 600 MHz band
    [1577755022, [617.00, 627.00]],
    
    # from CSD 2080 (2019/07/21 - ) Blobs, Channels 55 and 56
    [1564051033, [716.00, 728.00]],
```

2023-02-01 20:19 UTC, jrs65 commented on ch_util/rfi.py
> +            continue
You can use Python's unpacking to stream line this
```suggestion
    for start_time, (fs, fe) in bad_frequencies:
        if start_time is None or timestamp >= start_time:
            tm = np.logical_and(freq_end > fs, freq_start < fe)
            mask = np.logical_or(mask, tm)
        else:
            continue
```
Also it's usually better to explicitly check for `None`, as for instance `start_time = 0.0` would give `True` for `not start_time`

2023-02-01 20:19 UTC, jrs65 commented on ch_util/rfi.py
> +        Start observing time (in unix time)
The parameters should be documented in order. So move `timestamp` lower down.

2023-02-01 20:19 UTC, jrs65 commented on ch_util/rfi.py
> +    freq_mask = frequency_mask(data.freq, data.time[0])
I personally like to always give the name for keyword arguments, e.g.
```suggestion
    freq_mask = frequency_mask(data.freq, timestamp=data.time[0])
```
This is somewhat optional, so pick your own preferred style, but it's probably clearer and easier with long argument lists where you don't necessarily remember the order.

2023-02-01 20:19 UTC, jrs65 commented on ch_util/rfi.py
> +    timestamp : float
This documentation needs to go one parameter lower.

2023-02-01 20:19 UTC, jrs65 commented on ch_util/rfi.py
> +    LSD-dependent static RFI flags are added.
The numpydoc docstring format has a fairly restricted style and as we auto build our documentation we mostly need to stick to it. The opening should generally be.
```
"""One opening sentence less than a line long.

An optional longer paragraph that can span multiple lines giving more details
about what the routine does and any nuances.

You can have additional paragraphs too.

Parameters
----------
...
```

In this particular case, probably expand your second sentence into a longer paragraph about what is being done.

2023-02-02 19:32 UTC, ljgray requested changes
Overall this is looking good. I just added a few comments. 

I made a comment in the associated `ch_pipeline` PR about rebasing the git commits which would apply here too. Also, I think that the .DS_Store files should be removed from the PR. (I believe that) they're Mac OS-specific binary files which contain some info about the local folder, so they probably just got included by accident when adding files to commit. I'll actually make a seperate PR to include them in the .gitignore file so they don't get added again.

2023-02-02 19:32 UTC, ljgray commented on ch_util/rfi.py
> +bad_frequencies = [
Since this was changed to a list from a numpy array, there's always the slight risk that some code that used it (and expected a numpy array) could break. I don't think this is used anywhere outside of the `frequency_mask` function, so it should be fine, but you might just want to do a quick skim through the major repos to make sure that it isn't going to break anything.

2023-02-02 19:32 UTC, ljgray commented on ch_util/rfi.py
> +        else:
The `else: continue` lines here don't have to be included, the behaviour will be the same without them

2023-02-02 19:32 UTC, ljgray commented on ch_util/rfi.py
> +    timestamp=None,
Again, I think that `timestamp` should be added as the last argument for the reasons above.

2023-02-02 19:32 UTC, ljgray commented on ch_util/rfi.py
> +        flag = ~frequency_mask(freq, timestamp)
Pass as a keyword argument instead of positional

2023-02-10 23:11 UTC, ljgray approved these changes

2023-02-10 23:21 UTC, merged