feat: site-specific frequency bin masking, adding KKO mask
chime-experiment/ch_util pull request #59
Opened 2023-06-01 21:09 UTC by aelanman

Enables `rfi.py:frequency_mask()` to accept an "instrument" parameter, so it will return a custom frequency mask for each outrigger site and CHIME.

The KKO mask is set up to cover several consistently contaminated frequency bins. Similar masks will be added for GBO and HCO when we have more/any data from each.

2023-06-06 19:31 UTC, jrs65 requested changes
I made a few comments, but added suggestions for how to implement then.

2023-06-06 19:31 UTC, jrs65 commented on ch_util/rfi.py
> +    if bad_freq is None:
This should probably just no-op.

2023-06-06 19:31 UTC, jrs65 commented on ch_util/rfi.py
> +    bad_freq = bad_frequencies[instrument]
```suggestion
    bad_freq = bad_frequencies.get(instrument, None)
```

2023-06-07 15:49 UTC, aelanman commented on ch_util/rfi.py
> +    if bad_freq is None:
I don't understand... just fail silently?

2023-06-07 15:50 UTC, aelanman commented on ch_util/rfi.py
> +    bad_freq = bad_frequencies[instrument]
I believe this is achieved by the changes you suggested, along with the check on line 487.

2023-06-07 15:53 UTC, jrs65 commented on ch_util/rfi.py
> +    if bad_freq is None:
Yeah, this is up for debate. It depends on what you think the behaviour is for when you give it an instrument name it recognises but no one has put in the RFI mask for yet. Fail loudly, or no-op? I think I could go either way, but I figured the most useful would be the latter.

2023-06-07 16:13 UTC, jrs65 commented on ch_util/rfi.py
> +    bad_freq = bad_frequencies[instrument]
Indeed.

2023-06-07 16:13 UTC, jrs65 approved these changes

2023-06-07 20:08 UTC, merged